# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lKOazkLCB69fBZH-6hu9fobJwQHW9Qtg
"""

"""
IMPORTS SECTION
"""
import keras
from keras.layers import Dense, Conv2D, BatchNormalization, Activation, Dropout, GlobalAveragePooling2D
from keras.layers import AveragePooling2D, Input, Flatten, MaxPooling2D
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras.callbacks import ReduceLROnPlateau
from keras.preprocessing.image import ImageDataGenerator
from keras.regularizers import l2
from keras import backend as K
from keras.models import Model
from keras.datasets import cifar10
from keras.layers.merge import concatenate
import numpy as np
import os
import argparse

os.environ['CUDA_DEVICE_ORDER']="PCI_BUS_ID";
os.environ['CUDA_VISIBLE_DEVICES']="0";

parser = argparse.ArgumentParser(description="Parsing command line argunments...")
parser.add_argument("-k", default=12, type=int, required=False, help="Wide parameter. Default: 3")
parser.add_argument("-depth", default=121, type=int, required=False, help="Desired depth of model. Default: 121")
parser.add_argument("-da", default=True, type=bool, required=False, help="Train CIFAR with Data Augmentation. Default: True")

args = parser.parse_args()

"""
LOAD AND PREPROCESS DATA
"""
# Load the CIFAR10 data.
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Input image dimensions.
input_shape = x_train.shape[1:]

# Normalize data.
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

# Subtracting pixel mean improves accuracy
subtract_pixel_mean = True

# Training parameters
batch_size = 128  # orig paper trained all networks with batch_size=128
epochs = 200
data_augmentation = args.da
num_classes = 10

# If subtract pixel mean is enabled
if subtract_pixel_mean:
    x_train_mean = np.mean(x_train, axis=0)
    x_train -= x_train_mean
    x_test -= x_train_mean

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
print('y_train shape:', y_train.shape)

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


"""
WIDE-RESNET
"""

#Parameter to compute the depth of the Resnet
k = args.k
#depth = ((args.depth - 4) // 3) // 2
#blocks = [depth for _ in range(4)]
#print("BLOCKS: " + str(blocks))
depth = args.depth

# Model name, depth and version
model_type = 'DenseNet-%d' % (depth)



def lr_schedule(epoch):

    lr = 1e-3
    if epoch > 180:
        lr *= 0.5e-3
    elif epoch > 160:
        lr *= 1e-3
    elif epoch > 120:
        lr *= 1e-2
    elif epoch > 80:
        lr *= 1e-1
    print('Learning rate: ', lr)
    return lr


def densenet_layer(inputs,
                 num_filters=16,
                 kernel_size=3,
                 strides=1,
                 activation='relu',
                 batch_normalization=True,
                 conv_first=True):

    conv = Conv2D(num_filters,
                  kernel_size=kernel_size,
                  strides=strides,
                  padding='same',
                  kernel_initializer='he_normal',
                  kernel_regularizer=l2(1e-4))

    x = inputs
    if conv_first:
        x = conv(x)
        
    else:
        if batch_normalization:
            x = BatchNormalization()(x)
        if activation is not None:
            x = Activation(activation)(x)
        x = conv(x)
    return x

def densenet_conv_layer(input_tensor, num_filters):
  x = BatchNormalization()(input_tensor)
  x = Activation("relu")(x)

  x = Conv2D(num_filters, (1,1), kernel_initializer='he_normal', padding="same")(x)

  x = BatchNormalization()(x)
  x = Activation("relu")(x)

  x = Conv2D(num_filters, (3,3), kernel_initializer='he_normal', padding="same")(x)

  return x

def densenet_dense_block(input_tensor, num_layers, num_filters, k):
  concat_list = [input_tensor]
  x = input_tensor
  for i in range(num_layers):
    conv_layer = densenet_conv_layer(x, num_filters)
    concat_list.append(conv_layer)

    x = concatenate([x, conv_layer])

    num_filters = num_filters + k

  return x, num_filters

def densenet_middle_block(input_tensor, num_filters):
  x = BatchNormalization()(input_tensor)
  x = Activation("relu")(x)
  x = Conv2D(num_filters, (1,1), kernel_initializer="he_normal", padding="same")(x)
  x = AveragePooling2D((2,2), strides=(2,2))(x)

  return x



def densenet(input_shape, blocks, num_classes=10, k=12):


    num_filters = k

    inputs = Input(shape=input_shape)
    x = Conv2D(num_filters, (3,3), kernel_initializer="he_normal", padding="same", strides=(2,2))(inputs)
    #x = BatchNormalization()(x)
    #x = MaxPooling2D((3,3), strides=(2,2))(x)
    #x = inputs
    # Instantiate the stack of residual units
    for i in range(len(blocks)):
        x, num_filters = densenet_dense_block(x, blocks[i], num_filters, k)
        if i < len(blocks) - 1:
          x = densenet_middle_block(x, num_filters)

    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    x = GlobalAveragePooling2D()(x)
    #x = Flatten()(x)
    outputs = Dense(num_classes, activation="softmax")(x)

  

    # Instantiate model.
    model = Model(inputs=inputs, outputs=outputs)
    return model



if depth==121:
  model = densenet(input_shape=input_shape, blocks=[6,12,24,16], k=k, num_classes=10)
elif depth==169:
  model = densenet(input_shape=input_shape, blocks=[6,12,32,32], k=k, num_classes=10)
elif depth==201:
  model = densenet(input_shape=input_shape, blocks=[6,12,48,32], k=k, num_classes=10)
elif depth==264:
  model = densenet(input_shape=input_shape, blocks=[6,12,64,48], k=k, num_classes=10)
else:
  raise Exception("Not standard depth")


#model = densenet(input_shape=input_shape, blocks=blocks, k=k, num_classes=10)


model.compile(loss='categorical_crossentropy',
              optimizer=Adam(learning_rate=lr_schedule(0)),
              metrics=['accuracy'])
model.summary()
print(model_type)

# Prepare model model saving directory.
save_dir = os.path.join(os.getcwd(), 'saved_models')
model_name = 'cifar10_%s_model.{epoch:03d}.h5' % model_type
if not os.path.isdir(save_dir):
    os.makedirs(save_dir)
filepath = os.path.join(save_dir, model_name)

# Prepare callbacks for model saving and for learning rate adjustment.
checkpoint = ModelCheckpoint(filepath=filepath,
                             monitor='val_acc',
                             verbose=1,
                             save_best_only=True)

lr_scheduler = LearningRateScheduler(lr_schedule)

lr_reducer = ReduceLROnPlateau(factor=np.sqrt(0.1),
                               cooldown=0,
                               patience=5,
                               min_lr=0.5e-6)

callbacks = [checkpoint, lr_reducer, lr_scheduler]

# Run training, with or without data augmentation.
if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(x_train, y_train,
              batch_size=batch_size,
              epochs=epochs,
              validation_data=(x_test, y_test),
              shuffle=True,
              callbacks=callbacks)
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        # set input mean to 0 over the dataset
        featurewise_center=False,
        # set each sample mean to 0
        samplewise_center=False,
        # divide inputs by std of dataset
        featurewise_std_normalization=False,
        # divide each input by its std
        samplewise_std_normalization=False,
        # apply ZCA whitening
        zca_whitening=False,
        # epsilon for ZCA whitening
        zca_epsilon=1e-06,
        # randomly rotate images in the range (deg 0 to 180)
        rotation_range=0,
        # randomly shift images horizontally
        width_shift_range=0.1,
        # randomly shift images vertically
        height_shift_range=0.1,
        # set range for random shear
        shear_range=0.,
        # set range for random zoom
        zoom_range=0.,
        # set range for random channel shifts
        channel_shift_range=0.,
        # set mode for filling points outside the input boundaries
        fill_mode='nearest',
        # value used for fill_mode = "constant"
        cval=0.,
        # randomly flip images
        horizontal_flip=True,
        # randomly flip images
        vertical_flip=False,
        # set rescaling factor (applied before any other transformation)
        rescale=None,
        # set function that will be applied on each input
        preprocessing_function=None,
        # image data format, either "channels_first" or "channels_last"
        data_format=None,
        # fraction of images reserved for validation (strictly between 0 and 1)
        validation_split=0.0)

    # Compute quantities required for featurewise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_train, y_train, batch_size=batch_size),
                        validation_data=(x_test, y_test),
                        epochs=epochs, verbose=1, workers=4,
                        callbacks=callbacks)

# Score trained model.
scores = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])
